### ISSUE TITLE
Wikipedia entries should be sanitized for reddit links

### ISSUE THREAD

**Issue by IcanMorris** [zpoon/runescape-wiki-reddit#1]
The link-generating line 34:` **[%s](%s)**` uses result_name and result_url without any further checks. 

While the wiki is smart enough to handle the missing closing parenthesis that occurs by the malformed link, the characters [,],(,),\ are prone to cause minor errors. At least those characters should be escaped for reddit. 

Example:  [[Bailing bucket (full)]]

**Comment by zpoon** [comment]
Fixed in 0a1e7128cf54d0be9d05ce824245f6f948d3c1c6, thanks!
