### ISSUE TITLE
Let the bot work on alternate subs.

### ISSUE THREAD

**Issue by raf-42** [zpoon/runescape-wiki-reddit#3]
Sometimes I want to tag something on the other wiki (oldschool while on r/runescape or rs3 while on 2007scape). I know the gloopybot on discord has this feature. So like for the RS3 discords [[Graardor]] will have the bot link https://runescape.wiki/w/General_Graardor, but if I were to type [[osrs:Graardor]], It'd link me https://oldschool.runescape.wiki/w/General_Graardor.

If you decide to implement this, might I suggest using that bot's list of terms/alternatives?

> RuneScape: r, rs3, rsw, rs, runescape
> Old School RuneScape: o, 2007, osrs, osw, osrsw, os, oldschool, 2007scape, oldschoolrunescape

Thanks!

**Comment by zpoon** [comment]
Good idea. I knew Gloopy did this and I've been meaning to replicate it here but just haven't gotten around to it yet. Might tackle it this weekend when I get some free time.

**Comment by zpoon** [comment]
I've added the ability to use modifiers to the bot using the terms you suggested and should be live now. Thanks for the suggestion again!
